_target_: nav123d.agents.constant_velocity_agent.ConstantVelocityAgent
_convert_: 'all'

trajectory_sampling:
  _target_: nav123d.datatypes.trajectory.TrajectorySampling
  _convert_: 'all'
  time_horizon: 4
  interval_length: 0.5
