_target_: nav123d.agents.transfuser.transfuser_agent.TransfuserAgent
_convert_: 'all'

trajectory_sampling:
  _target_: nav123d.datatypes.trajectory.TrajectorySampling
  _convert_: 'all'
  time_horizon: 4
  interval_length: 0.5
config:
  _target_: nav123d.agents.transfuser.transfuser_config.TransfuserConfig
  _convert_: 'all'
  latent: false
checkpoint_path: null
lr: 1e-4
